src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AuthorRepository::class)
 */
class Author
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $company;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $short_bio;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $linkedin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $gitlab;

    /**
     * @ORM\OneToMany(targetEntity=Article::class, mappedBy="author", orphanRemoval=true)
     */
    private $articles;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="author")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(?string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getShortBio(): ?string
    {
        return $this->short_bio;
    }

    public function setShortBio(?string $short_bio): self
    {
        $this->short_bio = $short_bio;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(?string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }

    public function getGitlab(): ?string
    {
        return $this->gitlab;
    }

    public function setGitlab(?string $gitlab): self
    {
        $this->gitlab = $gitlab;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setAuthor($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getAuthor() === $this) {
                $article->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function __toString(): ?string
    {
        return $this->name;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Paragraph.php
<?php

namespace App\Entity;

use App\Repository\ParagraphRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=ParagraphRepository::class)
 */
class Paragraph
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="paragraphs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    /**
     * @ORM\OneToMany(targetEntity=ParagraphPicture::class, mappedBy="paragraphs", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $paragraphPictures;

    public function __construct()
    {
        $this->blogPictures = new ArrayCollection();
        $this->paragraphPictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return string|null
     */
    public function __toString(): ?string
    {
        return $this->slug;
    }

    /**
     * @return Collection|ParagraphPicture[]
     */
    public function getParagraphPictures(): Collection
    {
        return $this->paragraphPictures;
    }

    public function addParagraphPicture(ParagraphPicture $paragraphPicture): self
    {
        if (!$this->paragraphPictures->contains($paragraphPicture)) {
            $this->paragraphPictures[] = $paragraphPicture;
            $paragraphPicture->setParagraphs($this);
        }

        return $this;
    }

    public function removeParagraphPicture(ParagraphPicture $paragraphPicture): self
    {
        if ($this->paragraphPictures->removeElement($paragraphPicture)) {
            // set the owning side to null (unless already changed)
            if ($paragraphPicture->getParagraphs() === $this) {
                $paragraphPicture->setParagraphs(null);
            }
        }

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Category;
use App\Repository\ArticleRepository;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/", name="blog_")
 */
class BlogController extends AbstractController
{
    /**
     * @Route("", name="index")
     *
     * @param ArticleRepository $articleRepository
     * @param CategoryRepository $categoryRepository
     * @return Response
     */
    public function index(ArticleRepository $articleRepository, CategoryRepository $categoryRepository): Response
    {
        $articles = $articleRepository->findAll();

        $categories = $categoryRepository->findAll();

        $url_slug = 'all';

        return $this->render('blog/index.html.twig', [
            'articles' => $articles,
            'categories' => $categories,
            'url_slug' => $url_slug,
        ]);
    }

    /**
     * @Route("/category/{slug}", name="category")
     *
     * @param Category $category
     * @param CategoryRepository $categoryRepository
     * @param string $slug
     * @return Response
     */
    public function byCategory(Category $category, CategoryRepository $categoryRepository, string $slug, Request $request): Response
    {
        $articles = $category->getArticles();

        $categories = $categoryRepository->findAll();

        $url_slug = $request->attributes->get('slug');

        return $this->render('blog/index.html.twig', [
            'articles' => $articles,
            'categories' => $categories,
            'url_slug' => $url_slug,
        ]);
    }

    /**
     * @Route("/show/{slug}", name="show")
     *
     * @param ArticleRepository $articleRepository
     * @param string $slug
     * @param Article $article
     * @return Response
     */
    public function show(ArticleRepository $articleRepository, string $slug, Article $article): Response
    {
        $slug = $article->getSlug();
        $articles = $articleRepository->findOneBy(['slug' => $slug]);

        return $this->render('blog/show.html.twig', [
            'article' => $article,
        ]);
    }
}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Bienvenue
{% endblock %}

{% block body %}
  <section class="row col-12 mt-5" style="padding-bottom: 5rem;">
    {# articles #}
    <div class="col-9 offset-1">
      <div class="card-deck">
        {% for article in articles %}
          <div class="card mb-5"
            style="min-width: 30rem; max-width: 40rem; border:none; box-shadow: 0 0  5px -2.5px">
            {% if article.thumbnail != null %}
              <img src="{{ asset(
                  'images/thumbnails/' ~ article.thumbnail
                )|imagine_filter('article_thumb') }}"
                class="card-img-top"
                alt="..." />
            {% else %}
              <img src="{{ asset(
                  'build/images/article.b0aaabc6.jpg'
                )|imagine_filter('article_thumb') }}"
                class="card-img-top"
                alt="..." />
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">
                {{ article.title }}
              </h5>
              <div class="card-text">
                {{ article.description|raw }}
              </div>
            </div>
            <div class="card-footer mt-0"
              style="background: none; border: none; display:inline-flex;">
              <a href="{{
                path(
                  'blog_show',
                  {
                    slug: article.slug
                  }
                )
                }}"
                class="card-link btn btn-warning col-3"
                style="max-width:fit-content;">
                Découvrir
              </a>
              <p class="text-right"
                style="width:fit-content; margin-left:auto;">
                <small>{{ article.updatedAt|date('d/m/Y') }}</small>
              </p>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

    {# categories #}
    <aside class="col-2" style="margin-left: auto;">
      <h3>
        Categories
      </h3>
      <ul class="list-group">
        {% if url_slug == 'all' %}
          <li style="border:none; background-color: transparent;"
            class="list-group-item list-group-item-action active p-0 m-1 d-flex w-75 justify-content-between align-items-center">
            <a href="{{ path('blog_index') }}"
              style="text-decoration:none; color: black; background-color: #ffc107;"
              class="pl-1 pr-1">
              All
            </a>
            <span class="badge badge-dark badge-pill">
              {{ articles|length }}
            </span>
          </li>
        {% else %}
          <li style="border:none;"
            class="list-group-item list-group-item-action p-0 m-1 d-flex w-75 justify-content-between align-items-center">
            <a href="{{ path('blog_index') }}"
              style="text-decoration:none; color: black;">
              All
            </a>
            <span class="badge badge-dark badge-pill">
              {{ articles|length }}
            </span>
          </li>
        {% endif %}
        {% for category in categories %}
          {% if category.articles.count != 0 %}
            {% if url_slug == category.slug and url_slug != 'all' %}
              <li style="border:none; background-color: transparent;"
                class="list-group-item list-group-item-action active p-0 m-1 d-flex w-75 justify-content-between align-items-center">
                <a href="{{
                  path(
                    'blog_category',
                    {
                      slug: category.slug
                    }
                  )
                  }}"
                  style="text-decoration:none; color: black; background-color: #ffc107;"
                  class="pl-1 pr-1">
                  {{ category.name }}
                </a>
                <span class="badge badge-dark badge-pill">
                  {{ category.articles.count }}
                </span>
              </li>
            {% else %}
              <li style="border:none;"
                class="list-group-item list-group-item-action p-0 m-1 d-flex w-75 justify-content-between align-items-center">
                <a href="{{
                  path(
                    'blog_category',
                    {
                      slug: category.slug
                    }
                  )
                  }}"
                  style="text-decoration:none; color: black;">
                  {{ category.name }}
                </a>
                <span class="badge badge-dark badge-pill">
                  {{ category.articles.count }}
                </span>
              </li>
            {% endif %}
            {# TODO: ajouter is active !!!! #}
          {% endif %}
        {% endfor %}
      </ul>
    </aside>
  </section>
{% endblock %}

templates/blog/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ article.title }}
{% endblock %}

{% block body %}
  <section class="mt-5" style="padding-bottom: 5rem;">
    <div class="container">
      <div class="mt-3">
        <h2>
          {{ article.title|title }}
        </h2>
        <p class="text-right">
          <small>{{ article.updatedAt|date('d/m/Y') }}</small>
        </p>
      </div>

      {% if article.description != null %}
        {{ article.description|raw }}
      {% endif %}

      <div class="mt-5">
        {% for paragraph in article.paragraphs %}
          <div>
            <h3 class="mt-3 mb-3 ml-3">
              {{ paragraph.title|title }}
            </h3>
            <div class="ml-5">
              {{ paragraph.content|raw }}
            </div>
            {% for picture in paragraph.paragraphPictures %}
              <div class="text-center mt-5">
                <img src="{{ asset(
                    'images/paragraph-pictures/' ~ picture.picture
                  )|imagine_filter('article_thumb') }}"
                  alt="" />
              </div>
            {% endfor %}
          </div>
        {% endfor %}
      </div>

      <div class="mt-5 mb-5">
        <h3 class="mt-3 mb-3">
          Sur l'auteur
        </h3>
        <div class="ml-3">
          <h4 style="display:inline-block; width: fit-content;">
            {{ article.author.name }}
          </h4>
          <p style="display:inline-block; width: fit-content;">
            <small><i>{{ article.author.title }}</i></small>
          </p>
          {{ article.author.shortBio|raw }}
          {% if article.author.linkedin != null %}
            <div>
              <a href="{{ article.author.linkedin }}"
                target="_blank"
                style="text-decoration:none;">
                <i class="fab fa-linkedin" style="font-size: 1.25rem;"></i>
                <span>{{ article.author.linkedin }}</span>
              </a>
            </div>
          {% endif %}
          {% if article.author.gitlab != null %}
            <div>
              <a href="{{ article.author.gitlab }}"
                target="_blank"
                style="text-decoration:none;">
                <i class="fab fa-gitlab" style="font-size: 1.25rem;"></i>
                <span>{{ article.author.gitlab }}</span>
              </a>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}